### ISSUE TITLE
invalid mod 

### ISSUE THREAD

**Issue by Confygurated** [pack-png-mods/seed-selector#1]
so multimc keeps telling me that the mod file or something is invalid.
how do i fix that?

**Comment by Earthcomputer** [comment]
Please can you show the error message

**Comment by Confygurated** [comment]
its on german but i can translate it

**Comment by Confygurated** [comment]
![image](https://user-images.githubusercontent.com/70959858/92509946-569e5300-f20b-11ea-812c-b4c47f922025.png)

**Comment by Earthcomputer** [comment]
Did you follow the instructions in the readme?

**Comment by Confygurated** [comment]
yes, it didnt worked

**Comment by Earthcomputer** [comment]
Read it more carefully.
